coverage:
    precision: 2
    round: down
    range: "70...90"

    status:
        project:
            default:
                threshold: 0.5%
        changes: no
        patch:
            default:
                target: 80%

comment: off
